# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MAqJ8nQ6YySAwvqT2_3d2sWN0bRS9XDY
"""

def secure_login_name():
  print("**WELCOME TO JACKSON STATE UNIVERSITY LOGIN NAME GENERATOR**")
  
  first_name= str(input("Enter your first name:  "))
  #Slice the first 3 characters
  set1= first_name[0:2]

  last_name= str(input("Enter your last name:  "))
  #Slice the first 3 characters
  set2= first_name[0:2]

  ID_Number= str(input("Enter your ID number:  "))
   #Slice the last 4 characters
  set3= first_name[-4: ]

  secure_login_name= set1+set2+set3

  return secure_login_name